x-kafka-bootstrap: &kafka-bootstrap kafka:9092

services:
  fleet_service:
    build: ./apps/fleet_service
    ports:
      - "8001:8001"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: *kafka-bootstrap
      LOG_LEVEL: INFO
    volumes:
      - ./apps/fleet_service/app:/code/app  # Volume for hot reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      kafka:
        condition: service_healthy
      kafka_init:
        condition: service_completed_successfully
      postgres_init:
        condition: service_completed_successfully

  delivery_service:
    build: ./apps/delivery_service
    ports:
      - "8002:8002"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: *kafka-bootstrap
      LOG_LEVEL: INFO
    volumes:
      - ./apps/delivery_service/app:/code/app  # Volume for hot reloading
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    depends_on:
      fleet_service:
        condition: service_started
      kafka:
        condition: service_healthy
      kafka_init:
        condition: service_completed_successfully
      postgres_init:
        condition: service_completed_successfully

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: msnpmGRoRQec4cZinkNi4Q
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: CLIENT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s
    # TODO : Add volumes for data persistence

  kafka_init:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BOOTSTRAP_SERVERS: *kafka-bootstrap
    depends_on:
      kafka:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./infra/kafka:/scripts
    entrypoint: ["sh", "/scripts/create_topics.sh"]
    command: []

  redpanda_console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: *kafka-bootstrap
    depends_on:
      kafka:
        condition: service_healthy
      kafka_init:
        condition: service_completed_successfully

  postgres:
    image: postgres:18.6-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_ADMIN_USER}" ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s

  postgres_init:
    image: postgres:18.6-bookworm
    environment:
      PGHOST: postgres
      PGUSER: ${POSTGRES_ADMIN_USER}
      PGPASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      FLEET_SERVICE_DB_PASSWORD: ${FLEET_SERVICE_DB_PASSWORD}
      DELIVERY_SERVICE_DB_PASSWORD: ${DELIVERY_SERVICE_DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./infra/postgres:/scripts
    entrypoint: [ "sh", "/scripts/init-databases.sh" ]
    command: [ ]

volumes:
  postgres_data:
