"""create journeys table

Revision ID: 3f7fea382d94
Revises: 
Create Date: 2026-10-03 12:07:19.829659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7fea382d94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journeys',
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('truck_id', sa.String(), nullable=False),
    sa.Column('pickup_lat', sa.Double(), nullable=False),
    sa.Column('pickup_lon', sa.Double(), nullable=False),
    sa.Column('dropoff_lat', sa.Double(), nullable=False),
    sa.Column('dropoff_lon', sa.Double(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index(op.f('ix_journeys_truck_id'), 'journeys', ['truck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journeys_truck_id'), table_name='journeys')
    op.drop_table('journeys')
    # ### end Alembic commands ###
