"""create deliveries table

Revision ID: 2083285b7227
Revises: 
Create Date: 2026-09-05 14:36:15.294677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2083285b7227'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pickup_location', sa.String(), nullable=False),
    sa.Column('dropoff_location', sa.String(), nullable=False),
    sa.Column('cargo_weight_kg', sa.Integer(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ASSIGNED', 'DENIED', 'COMPLETED', name='deliverystatus'), nullable=False),
    sa.Column('assigned_truck_id', sa.String(), nullable=True),
    sa.Column('denial_reason', sa.Enum('INVALID_REQUEST', 'NO_AVAILABLE_TRUCK', name='deliverydenialreason'), nullable=True),
    sa.Column('denial_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    # ### end Alembic commands ###
