name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tests:
    strategy:
      matrix:
        service: ["fleet_service", "delivery_service", "gps_simulator"]
      fail-fast: false
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: apps/${{ matrix.service }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup uv
        uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
        with:
          version: "0.13.0"

      - name: Install dependencies
        run: uv sync --locked

      - name: Run tests
        run: uv run pytest test -q --cov --cov-report=term --cov-report=xml

      - name: Create job summary
        if: ${{ !cancelled() }}
        run: |
          echo "# ${{ matrix.service }} test report" >> "$GITHUB_STEP_SUMMARY"
          uv run coverage report --format=markdown >> "$GITHUB_STEP_SUMMARY"

      - name: Upload results to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.service }}
          fail_ci_if_error: true
    timeout-minutes: 4